config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # ユーザの新規登録URLを /signupにするための設定。
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create] do
    # 中間テーブル関連のルーティング。フォロー中のユーザとフォローされているユーザ、お気に入り登録しているユーザの一覧を表示。
    member do 
      get :followings
      get :followers
      get :likes
    end
  end

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    # 重複を許さないバリデーション。大文字と小文字を区別せず同一のものとして処理する。
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  # 一対多の関係を記述。
  has_many :microposts
  has_many :relationships
  
  # フォローしているUser達を表現。through: :relationshipsでhas_many: relationshipsの結果を中間テーブルを指定。
  # source: :followで中間テーブルのカラムの中でどのidを参照するか決定している。
  has_many :followings, through: :relationships, source: :follow
  
  # 順方向に対して逆の設定。
  has_many :reverses_of_relationship, class_name: "Relationship", foreign_key: "follow_id"
  
  # source: :userで中間テーブルの user_idを取得したいUserと指定している。
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorites
  has_many :favorite_microposts, through: :favorites, source: :micropost
  
  # フォロー用のメソッド
  def follow(other_user)
    unless self == other_user # フォローしようとしている other_user が自分自身でないことを検証。
     self.relationships.find_or_create_by(follow_id: other_user.id) # selfには user.follow(other)を実行したときuserが代入される。
    end
  end
   
  def unfollow(other_user) # フォローがあればアンフォローする。
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship # relationshipが存在すればdestroyする。
  end
  
  def following?(other_user)
    self.followings.include?(other_user) # self.followingsでフォローしているUserを取得、inclide?(other_user)でother_userが含まれていないかを確認。含まれていればtrue、なければfalseを返す。
  end
  
  # タイムライン用のメソッド
  def feed_microposts
    Micropost.where(user_id:self.following_ids + [self.id])
  end
  
  # お気に入り登録用のメソッド
  def favorite(micropost)
    self.favorites.find_or_create_by(micropost_id: micropost.id)
  end
  
  def unfavorite(micropost)
    favorite = self.favorites.find_by(micropost_id: micropost.id)
    favorite.destroy if favorite
  end
  
  def favorite_micropost?(micropost)
    self.favorite_microposts.include?(micropost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # アクションが実行される前に、前もって実行すべきアクションが記述されている。
  # ユーザがログインしていなければ操作できないアクションが記述されている。
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers, :likes]
  
  # idのカラムを基準にdesc(降順)にuserが表示される。今回の場合1ページ当たり、25件のユーザが表示。
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id]) # userのレコードの１つを、paramsによってURLのパラメータやデータを全て受け取れる
    @microposts = @user.microposts.order(id: :desc).page(params[:page])
    counts(@user)
  end
  
  def new
    @user= User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user 
    else
    # 登録に失敗した場合、newファイルを表示する。
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def followings 
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @favorite_microposts = @user.favorite_microposts.page(params[:page])
    counts(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    #requireでPOSTで受け取る値のキーを設定。
    #permitで許可するカラムを設定。ここではname, email, password属性の値だけDBに入れるのを許可。
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <!-- link_toメソッドで userのshowアクションへリンクされる。 -->
            <p><%= link_to 'View profile', user %></p> 
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Microposts  <span class="badge badge-secondary"><%= @count_microposts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Favorites <span class="badge badge-secondary"><%= @count_favorite_microposts %></span></a></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Microposts  <span class="badge badge-secondary"><%= @count_microposts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Favorites <span class="badge badge-secondary"><%= @count_favorite_microposts %></span></a></li>
  </ul>
  <%= render 'users', users: @followings %>
 </div>
</div>

app/views/users/index.html.erb
<!-- render "users"で _users.html.erbパーシャルを埋め込んでいる。 -->
<!-- users: @usersはパーシャルに対して変数を渡しており、usersという変数名で@usersの値を渡している。 -->
<%= render "users", users: @users %>

app/views/users/likes.html.erb
<!-- お気に入り登録/解除ボタンの設置 -->

<div class="row">
  <aside class="col-sm-4">
    <div class="card">
     <div class="card-header">
      <h3 class="card-title"><%= @user.name %></h3>
     </div>
    <div class="card-body">
      <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
    </div>
  </div>
   <%= render "relationships/follow_button", user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= "active" if current_page?(user_path(@user)) %>">Microposts  <span class="badge badge-secondary"><%= @count_microposts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= "active" if current_page?(likes_user_path(@user)) %>">Favorites <span class="badge badge-secondary"><%= @count_favorite_microposts %></span></a></li>
    </ul>
  <%= render 'microposts/microposts', microposts: @favorite_microposts %>
  </div>
</div>

app/views/users/new.html.erb
<!-- ユーザ登録用のフォーム -->
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <!-- form_with(model: @user...) は Controllerのnewアクションで用意した @userを使用してフォームを作ることを明示している。 -->
    <%= form_with(model: @user, local: true) do |f| %>
      <!-- model: f.objectは@userが代入されている。 -->
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!-- ユーザ詳細ページ -->
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render "relationships/follow_button", user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Microposts  <span class="badge badge-secondary"><%= @count_microposts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Favorites <span class="badge badge-secondary"><%= @count_favorite_microposts %></span></a></li>
    </ul>
    <%= render "microposts/microposts", microposts: @microposts %>
  </div>
</div>